#!/bin/sh

# 
if [ -f $ZDOTDIR/.dircolors ]; then
	if type dircolors > /dev/null 2>&1; then
		eval $(dircolors $ZDOTDIR/.dircolors)
	elif type gdircolors > /dev/null 2>&1; then
		eval $(gdircolors $ZDOTDIR/.dircolors)
	fi
fi


